language: node_js

node_js:
  - node

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run build
  - npm test

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

before_deploy:
  - mkdir deploy
  - mv dist deploy/dist
  - mv index.html deploy/index.html
  - mv sw.js deploy/sw.js

deploy:
  local-dir: deploy
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

after_success: npm run coverage
