language: node_js

node_js:
  - node

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm test

cache:
  directories:
  - node_modules

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
  - master

after_success: npm run coverage
